### ISSUE TITLE
undefined variable: anniValidi

### ISSUE THREAD

**Issue by adefaveri** [proviniciacremona/AVCP-Xml#5]
Inserendo una gara per il nuovo anno restituisce un errore e un avviso nel file resume.php:
PHP Notice:  Undefined variable: anniValidi in app/resume.php on line 17, referer: http://****/?mask=signin&do=login
PHP Fatal error:  Uncaught Error: Class 'ZipArchive' not found in resume.php:193\nStack trace:\n#0 {main}\n  thrown in app/resume.php on line 193, referer: http://*****/?mask=signin&do=login

versione 0.7.2

**Comment by ClaudioRoncaglio** [comment]
Possibile che stia testando il software con una versione di php  minore della 5.2? Chiedo perché ZipArchive è una classe di php.

**Comment by adefaveri** [comment]
Stiamo utilizzando la PHP Version 7.0.22

**Comment by ClaudioRoncaglio** [comment]
Il programma è connesso al database e funzionante? Lo stavate già usando o è un tentativo di nuova installazione?  

Chiedo perché la variabile anniValidi viene dichiarata esplicitamente appena dopo la connessione al db e non vedo come possa essere vuota... a meno che non fallisca la connessione al db.

L'errore sulla classe ZipArchive invece mi fa pensare che non sia installata l'estensione Zip di php.
